wandb_version: 1

learning_rate:
  desc: null
  value: 0.001
batch_size:
  desc: null
  value: 64
num_epochs:
  desc: null
  value: 20
num_workers:
  desc: null
  value: 8
architecture:
  desc: null
  value: U-Net
dataset:
  desc: null
  value: Cityscapes
optimizer:
  desc: null
  value: Adam
scheduler:
  desc: null
  value: StepLR
scheduler_step_size:
  desc: null
  value: 10
scheduler_gamma:
  desc: null
  value: 0.1
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1710412713.0
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 1
      - 16
      - 23
      4: 3.10.12
      5: 0.16.4
      8:
      - 8
      13: linux-x86_64
